# Generated by Django 5.0.1 on 2024-01-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appuser_is_active_appuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_staff',
        ),
    ]
